### DISCUSSION TITLE
Hardware acceleration?

### DISCUSSION THREAD

**Discussion by danuals** [weltenwort/frigate-synology-dsm7#10] [Q&A]
Thanks for this, running in a dd220+ with coral usb.

is hardware acceleration possible or a benefit?

**Comment by weltenwort** [comment]
The Coral USB device is a hardware accelerator for inference. Are you asking about video encoding/decoding acceleration in addition to that?

**Comment by danuals** [comment]
Yes. Hw accel args, wondered if it’s possible and what benefit it would be

**Reply by weltenwort** [reply]
They are no different from the official image (https://docs.frigate.video/configuration/hardware_acceleration). I'm using the following config on my intel-based disk station, but it looks like the CPU is still heavily involved in the image scaling:

```yaml
ffmpeg:
  hwaccel_args:
    - "-hwaccel"
    - "qsv"
    - "-qsv_device"
    - "/dev/dri/renderD128"
```

So I'm still looking for the right way to configure `ffmpeg` to use acceleration for that too :shrug: If you find out anything I'd be interested to hear about it.
